/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class RuscButton {
  /** Create a new Button */
  static new(): RuscButton
  /** Set the button caption/text */
  setCaption(caption: string): this
  /** Set the VBA macro to run when button is clicked */
  setMacro(macroName: string): this
  /** Set the button width in pixels */
  setWidth(width: number): this
  /** Set the button height in pixels */
  setHeight(height: number): this
  /** Set the button alt text for accessibility */
  setAltText(altText: string): this
  /** Set how the button moves and sizes with cells */
  setObjectMovement(option: string): this
}

/** Chart wrapper for Excel charts */
export declare class RuscChart {
  /** Create a new chart with the specified type */
  constructor(chartType: string)
  /** Add a data series to the chart */
  addSeries(categories: string | undefined | null, values: string, name?: string | undefined | null): void
  /** Set the chart title */
  setTitle(title: string): void
  /** Set the X-axis label */
  setXAxisName(name: string): void
  /** Set the Y-axis label */
  setYAxisName(name: string): void
  /** Set the chart style (1-48) */
  setStyle(style: number): void
  /** Hide the chart legend */
  setLegendHidden(): void
}

export declare class RuscDataValidation {
  /** Create a new data validation with "any value" type */
  constructor()
  /** Allow whole number validation */
  allowWholeNumber(rule: string, value: number): void
  /** Allow whole number validation between two values */
  allowWholeNumberBetween(min: number, max: number): void
  /** Allow decimal number validation */
  allowDecimalNumber(rule: string, value: number): void
  /** Allow decimal number validation between two values */
  allowDecimalNumberBetween(min: number, max: number): void
  /** Allow list validation with strings */
  allowListStrings(list: Array<string>): void
  /** Allow list validation from a formula/cell range */
  allowListFormula(formula: string): void
  /** Allow custom formula validation */
  allowCustom(formula: string): void
  /** Allow any value (mainly used for input messages) */
  allowAnyValue(): void
  /** Set whether to ignore blank cells */
  ignoreBlank(enable: boolean): void
  /** Set whether to show the dropdown arrow */
  showDropdown(enable: boolean): void
  /** Set whether to show the input message */
  showInputMessage(enable: boolean): void
  /** Set whether to show the error message */
  showErrorMessage(enable: boolean): void
  /** Set the input message title */
  setInputTitle(title: string): void
  /** Set the input message text */
  setInputMessage(message: string): void
  /** Set the error message title */
  setErrorTitle(title: string): void
  /** Set the error message text */
  setErrorMessage(message: string): void
  /** Set the error style */
  setErrorStyle(style: string): void
}

export declare class RuscDocProperties {
  /** Create a new DocProperties struct */
  static new(): RuscDocProperties
  /** Set the document author */
  setAuthor(author: string): this
  /** Set the document title */
  setTitle(title: string): this
  /** Set the document subject */
  setSubject(subject: string): this
  /** Set the document comment */
  setComment(comment: string): this
  /** Set the document company */
  setCompany(company: string): this
  /** Set the document manager */
  setManager(manager: string): this
  /** Set the document status */
  setStatus(status: string): this
  /** Set the document category */
  setCategory(category: string): this
  /** Set the document keywords */
  setKeywords(keywords: string): this
  /** Set the document hyperlink base */
  setHyperlinkBase(base: string): this
}

export declare class RuscFormat {
  /** Create a new format */
  constructor()
  /** Set bold text */
  setBold(): void
  /** Set italic text */
  setItalic(): void
  /** Set font size */
  setFontSize(size: number): void
  /** Set font color */
  setFontColor(color: string): void
  /** Set background color */
  setBackgroundColor(color: string): void
  /** Set horizontal alignment */
  setAlign(align: string): void
  /** Set vertical alignment */
  setVerticalAlign(align: string): void
  /** Set border style */
  setBorder(border: string): void
  /** Set number format */
  setNumFormat(numFormat: string): void
  /** Set font name (e.g., 'Arial', 'Calibri', 'Times New Roman') */
  setFontName(fontName: string): void
  /** Set text underline style */
  setUnderline(underline: string): void
  /** Set strikethrough text */
  setStrikethrough(): void
  /** Set foreground color (for patterns) */
  setForegroundColor(color: string): void
  /** Set fill pattern */
  setPattern(pattern: string): void
  /** Enable text wrapping in the cell */
  setTextWrap(): void
  /** Set text indentation level (0-15) */
  setIndent(indent: number): void
  /** Set text rotation in degrees (-90 to 90, or 270 for vertical text) */
  setRotation(rotation: number): void
  /** Shrink text to fit cell */
  setShrink(): void
  /** Set top border style */
  setBorderTop(border: string): void
  /** Set bottom border style */
  setBorderBottom(border: string): void
  /** Set left border style */
  setBorderLeft(border: string): void
  /** Set right border style */
  setBorderRight(border: string): void
  /** Set color for all borders */
  setBorderColor(color: string): void
  /** Set top border color */
  setBorderTopColor(color: string): void
  /** Set bottom border color */
  setBorderBottomColor(color: string): void
  /** Set left border color */
  setBorderLeftColor(color: string): void
  /** Set right border color */
  setBorderRightColor(color: string): void
  /** Unlock cell (for use with worksheet protection) */
  setUnlocked(): void
  /** Lock cell (cell will be protected when worksheet is protected) */
  setLocked(): void
  /** Hide formulas in cell (for use with worksheet protection) */
  setHidden(): void
  /** Set font script (superscript or subscript) */
  setFontScript(script: string): void
  /** Set diagonal border style */
  setBorderDiagonal(border: string): void
  /** Set diagonal border color */
  setBorderDiagonalColor(color: string): void
  /** Set diagonal border type (up, down, or both) */
  setBorderDiagonalType(borderType: string): void
  /** Set reading direction (0=context, 1=left-to-right, 2=right-to-left) */
  setReadingDirection(direction: number): void
  /** Set quote prefix (force string interpretation with leading apostrophe) */
  setQuotePrefix(): void
}

export declare class RuscFormula {
  /** Create a new formula */
  constructor(formula: string)
  /** Set the result value for the formula (for apps that don't auto-calculate) */
  setResult(result: string): void
}

/** Wrapper for Image to insert images into worksheets */
export declare class RuscImage {
  /**
   * Create a new Image from a file path
   * Supports PNG, JPG, GIF, and BMP formats
   */
  static new(path: string): RuscImage
  /** Create an Image from a buffer (u8 array) */
  static newFromBuffer(buffer: Buffer): RuscImage
  /** Set the width of the image in pixels */
  setWidth(width: number): this
  /** Set the height of the image in pixels */
  setHeight(height: number): this
  /** Scale the width of the image as a percentage */
  setScaleWidth(scale: number): this
  /** Scale the height of the image as a percentage */
  setScaleHeight(scale: number): this
  /** Scale the image to a specific size maintaining or ignoring aspect ratio */
  setScaleToSize(width: number, height: number, keepAspectRatio: boolean): this
  /** Set alt text for the image (for accessibility) */
  setAltText(altText: string): this
  /** Set the image as decorative (no alt text required) */
  setDecorative(enable: boolean): this
  /**
   * Set how the image moves and sizes with cells
   * Options: 'moveAndSize', 'moveOnly', 'none', 'moveAndSizeAfter'
   */
  setObjectMovement(option: string): this
  /** Add a URL link to the image */
  setUrl(url: string): this
}

export declare class RuscNote {
  /** Create a new note with text */
  constructor(text: string)
  /** Set the author name for the note */
  setAuthor(name: string): void
  /** Set the width of the note in pixels */
  setWidth(width: number): void
  /** Set the height of the note in pixels */
  setHeight(height: number): void
  /** Set the background color of the note */
  setBackgroundColor(color: string): void
  /** Make the note visible by default (normally it's hidden until you hover over the cell) */
  setVisible(visible: boolean): void
  /** Set alt text for accessibility */
  setAltText(altText: string): void
}

/** Wrapper for ProtectionOptions to configure worksheet protection */
export declare class RuscProtectionOptions {
  /** Create a new ProtectionOptions object with default settings */
  constructor()
  /** Allow or prevent users from selecting locked cells (default: true) */
  setSelectLockedCells(allow: boolean): this
  /** Allow or prevent users from selecting unlocked cells (default: true) */
  setSelectUnlockedCells(allow: boolean): this
  /** Allow or prevent users from formatting cells (default: false) */
  setFormatCells(allow: boolean): this
  /** Allow or prevent users from formatting columns (default: false) */
  setFormatColumns(allow: boolean): this
  /** Allow or prevent users from formatting rows (default: false) */
  setFormatRows(allow: boolean): this
  /** Allow or prevent users from inserting columns (default: false) */
  setInsertColumns(allow: boolean): this
  /** Allow or prevent users from inserting rows (default: false) */
  setInsertRows(allow: boolean): this
  /** Allow or prevent users from inserting hyperlinks (default: false) */
  setInsertLinks(allow: boolean): this
  /** Allow or prevent users from deleting columns (default: false) */
  setDeleteColumns(allow: boolean): this
  /** Allow or prevent users from deleting rows (default: false) */
  setDeleteRows(allow: boolean): this
  /** Allow or prevent users from sorting data (default: false) */
  setSort(allow: boolean): this
  /** Allow or prevent users from using autofilters (default: false) */
  setUseAutofilter(allow: boolean): this
  /** Allow or prevent users from using pivot tables (default: false) */
  setUsePivotTables(allow: boolean): this
  /** Allow or prevent users from editing scenarios (default: false) */
  setEditScenarios(allow: boolean): this
  /** Allow or prevent users from editing objects like images (default: false) */
  setEditObjects(allow: boolean): this
  /** Allow or prevent editing contents in chartsheets (default: true) */
  setContents(allow: boolean): this
}

/** Wrapper for rich text strings (multi-format text in a single cell) */
export declare class RuscRichText {
  /** Create a new empty rich text string */
  constructor()
  /**
   * Add a text segment with formatting
   * The format is cloned internally for storage
   */
  addSegment(text: string, format: RuscFormat): this
}

export declare class RuscShape {
  /** Create a new textbox shape */
  static textbox(): RuscShape
  /** Set the text content of the textbox */
  setText(text: string): this
  /** Set the width in pixels */
  setWidth(width: number): this
  /** Set the height in pixels */
  setHeight(height: number): this
  /** Set the alt text for accessibility */
  setAltText(altText: string): this
  /** Set how the shape moves and sizes with cells */
  setObjectMovement(option: string): this
}

export declare class RuscSparkline {
  /** Create a new Sparkline */
  static new(): RuscSparkline
  /** Set the data range for the sparkline (e.g., "Sheet1!A1:E1") */
  setRange(range: string): this
  /** Set the type of sparkline: 'line', 'column', or 'winLose' */
  setType(sparklineType: string): this
  /** Show markers for the highest point */
  showHighPoint(enable: boolean): this
  /** Show markers for the lowest point */
  showLowPoint(enable: boolean): this
  /** Show markers for the first point */
  showFirstPoint(enable: boolean): this
  /** Show markers for the last point */
  showLastPoint(enable: boolean): this
  /** Show markers for negative points */
  showNegativePoints(enable: boolean): this
  /** Show markers for all points */
  showMarkers(enable: boolean): this
  /** Show the horizontal axis */
  showAxis(enable: boolean): this
  /** Show data from hidden rows/columns */
  showHiddenData(enable: boolean): this
  /** Display sparkline right to left */
  setRightToLeft(enable: boolean): this
  /** Set the color of the sparkline (hex color like "#FF0000") */
  setSparklineColor(color: string): this
  /** Set the color of the high point marker */
  setHighPointColor(color: string): this
  /** Set the color of the low point marker */
  setLowPointColor(color: string): this
  /** Set the color of the first point marker */
  setFirstPointColor(color: string): this
  /** Set the color of the last point marker */
  setLastPointColor(color: string): this
  /** Set the color of negative point markers */
  setNegativePointsColor(color: string): this
  /** Set the color of all point markers */
  setMarkersColor(color: string): this
  /** Set the line weight/width */
  setLineWeight(weight: number): this
  /** Set the custom maximum value for vertical axis */
  setCustomMax(max: number): this
  /** Set the custom minimum value for vertical axis */
  setCustomMin(min: number): this
  /** Set maximum value based on group maximum */
  setGroupMax(enable: boolean): this
  /** Set minimum value based on group minimum */
  setGroupMin(enable: boolean): this
  /** Set a predefined style (1-36) */
  setStyle(style: number): this
  /** Set how empty cells are displayed: 'gaps', 'zero', or 'connected' */
  showEmptyCellsAs(option: string): this
}

export declare class RuscTable {
  /** Create a new Table */
  static new(): RuscTable
  /** Set whether the table has a header row */
  setHeaderRow(show: boolean): this
  /** Set whether the table has a total row */
  setTotalRow(show: boolean): this
  /** Set whether the table has banded rows */
  setBandedRows(show: boolean): this
  /** Set whether the table has banded columns */
  setBandedColumns(show: boolean): this
  /** Set whether the first column is formatted */
  setFirstColumn(show: boolean): this
  /** Set whether the last column is formatted */
  setLastColumn(show: boolean): this
  /** Set the name of the table */
  setName(name: string): this
  /** Set the style of the table (1-21 for light styles, 22-49 for medium styles, 50-61 for dark styles) */
  setStyle(styleId: number): this
  /** Add columns to the table */
  setColumns(columns: Array<RuscTableColumn>): this
}

export declare class RuscTableColumn {
  /** Create a new table column */
  static new(): RuscTableColumn
  /** Set the header name for the column */
  setHeader(header: string): this
  /** Set the total function for the column */
  setTotalFunction(func: string): this
  /** Set a custom total label for the column */
  setTotalLabel(label: string): this
  /** Set a custom formula for the column */
  setFormula(formula: string): this
}

/** Workbook wrapper for Excel file creation */
export declare class RuscWorkbook {
  /** Create a new workbook */
  constructor()
  /** Add a new worksheet to the workbook and return a reference to it */
  addWorksheet(name?: string | undefined | null): RuscWorksheet
  /** Add a new worksheet with constant memory mode to the workbook */
  addWorksheetWithConstantMemory(name?: string | undefined | null): RuscWorksheet
  /** Add a new worksheet with low memory mode to the workbook */
  addWorksheetWithLowMemory(name?: string | undefined | null): RuscWorksheet
  /** Set a custom temporary directory for constant memory mode */
  setTempdir(dir: string): void
  /** Save the workbook to a file */
  save(filename: string): void
  /** Save the workbook to a buffer */
  saveToBuffer(): Buffer
  /**
   * Define a named range or formula
   *
   * # Arguments
   *
   * * `name` - The name for the range (e.g., "Sales" or "Sheet1!Sales" for local names)
   * * `formula` - The formula or range (e.g., "=Sheet1!$A$1:$A$10" or "=SUM(A1:A10)")
   */
  defineName(name: string, formula: string): void
  /** Set the workbook to be opened in read-only recommended mode */
  readOnlyRecommended(): void
  /**
   * Add a VBA macro file to the workbook
   *
   * # Arguments
   *
   * * `path` - Path to the vbaProject.bin file
   */
  addVbaProject(path: string): void
  /**
   * Set document properties (metadata) for the workbook
   *
   * # Arguments
   *
   * * `properties` - DocProperties object with metadata
   */
  setProperties(properties: RuscDocProperties): void
}

/** Worksheet wrapper for Excel sheet manipulation */
export declare class RuscWorksheet {
  /** Write a value to a cell (auto-detects type) */
  write(row: number, col: number, value: string | number | boolean, format?: RuscFormat | undefined | null): void
  /** Write a string to a cell */
  writeString(row: number, col: number, value: string): void
  /** Write a number to a cell */
  writeNumber(row: number, col: number, value: number): void
  /** Write a boolean to a cell */
  writeBoolean(row: number, col: number, value: boolean): void
  /** Write a blank cell with formatting */
  writeBlank(row: number, col: number, format: RuscFormat): void
  /** Write a rich text string (multi-format text) to a cell */
  writeRichString(row: number, col: number, richText: RuscRichText): void
  /** Write a rich text string with an additional cell format */
  writeRichStringWithFormat(row: number, col: number, richText: RuscRichText, cellFormat: RuscFormat): void
  /** Write a datetime from a Unix timestamp (seconds since 1970-01-01 UTC) */
  writeDatetimeFromTimestamp(row: number, col: number, timestamp: number, format?: RuscFormat | undefined | null): void
  /** Write a datetime from year, month, day components */
  writeDatetimeFromYmd(row: number, col: number, year: number, month: number, day: number, format?: RuscFormat | undefined | null): void
  /** Write a datetime from year, month, day, hour, minute, second components */
  writeDatetimeFromYmdHms(row: number, col: number, year: number, month: number, day: number, hour: number, min: number, sec: number, format?: RuscFormat | undefined | null): void
  /** Write a datetime from an ISO 8601 string (e.g., "2023-01-25T12:30:00") */
  writeDatetimeFromString(row: number, col: number, datetimeStr: string, format?: RuscFormat | undefined | null): void
  /** Write a value with formatting to a cell */
  writeWithFormat(row: number, col: number, value: string | number | boolean, format: RuscFormat): void
  /** Set the width of a column */
  setColumnWidth(col: number, width: number): void
  /** Set the height of a row */
  setRowHeight(row: number, height: number): void
  /** Set the name of the worksheet */
  setName(name: string): void
  /** Merge a range of cells */
  mergeRange(firstRow: number, firstCol: number, lastRow: number, lastCol: number, value: string, format?: RuscFormat | undefined | null): void
  /** Merge a range of cells with formatting */
  mergeRangeWithFormat(firstRow: number, firstCol: number, lastRow: number, lastCol: number, value: string, format: RuscFormat): void
  /** Insert a note (post-it style comment) to a cell */
  insertNote(row: number, col: number, note: RuscNote): void
  /** Set the default author name for all notes in the worksheet */
  setDefaultNoteAuthor(name: string): void
  /** Write a formula to a cell */
  writeFormula(row: number, col: number, formula: RuscFormula, format?: RuscFormat | undefined | null): void
  /** Write a dynamic array formula to a cell (Excel 365) */
  writeDynamicFormula(row: number, col: number, formula: RuscFormula, format?: RuscFormat | undefined | null): void
  /** Write an array formula to a range of cells */
  writeArrayFormula(firstRow: number, firstCol: number, lastRow: number, lastCol: number, formula: RuscFormula, format?: RuscFormat | undefined | null): void
  /** Add data validation to a cell or range */
  addDataValidation(firstRow: number, firstCol: number, lastRow: number, lastCol: number, validation: RuscDataValidation): void
  /** Write a URL to a cell */
  writeUrl(row: number, col: number, url: string, format?: RuscFormat | undefined | null): void
  /** Write a URL to a cell with custom display text */
  writeUrlWithText(row: number, col: number, url: string, text: string, format?: RuscFormat | undefined | null): void
  /** Set autofilter on a range */
  autofilter(firstRow: number, firstCol: number, lastRow: number, lastCol: number): void
  /** Freeze panes at the specified row and column */
  setFreezePanes(row: number, col: number): void
  /** Add 2-color scale conditional formatting */
  addConditionalFormat2ColorScale(firstRow: number, firstCol: number, lastRow: number, lastCol: number, minColor: string, maxColor: string): void
  /** Add 3-color scale conditional formatting */
  addConditionalFormat3ColorScale(firstRow: number, firstCol: number, lastRow: number, lastCol: number, minColor: string, midColor: string, maxColor: string): void
  /** Add data bar conditional formatting */
  addConditionalFormatDataBar(firstRow: number, firstCol: number, lastRow: number, lastCol: number, barColor: string): void
  /** Add cell-based conditional formatting (greater than, less than, etc.) */
  addConditionalFormatCell(firstRow: number, firstCol: number, lastRow: number, lastCol: number, rule: string, value: number, format: RuscFormat): void
  /** Add text-based conditional formatting */
  addConditionalFormatText(firstRow: number, firstCol: number, lastRow: number, lastCol: number, rule: string, text: string, format: RuscFormat): void
  /** Add average/standard deviation conditional formatting */
  addConditionalFormatAverage(firstRow: number, firstCol: number, lastRow: number, lastCol: number, rule: string, format: RuscFormat): void
  /** Add top/bottom N conditional formatting */
  addConditionalFormatTop(firstRow: number, firstCol: number, lastRow: number, lastCol: number, rule: string, value: number, format: RuscFormat): void
  /** Add duplicate/unique values conditional formatting */
  addConditionalFormatDuplicate(firstRow: number, firstCol: number, lastRow: number, lastCol: number, invert: boolean, format: RuscFormat): void
  /** Add blank/non-blank conditional formatting */
  addConditionalFormatBlank(firstRow: number, firstCol: number, lastRow: number, lastCol: number, invert: boolean, format: RuscFormat): void
  /** Add error/non-error conditional formatting */
  addConditionalFormatError(firstRow: number, firstCol: number, lastRow: number, lastCol: number, invert: boolean, format: RuscFormat): void
  /** Add date-based conditional formatting */
  addConditionalFormatDate(firstRow: number, firstCol: number, lastRow: number, lastCol: number, rule: string, format: RuscFormat): void
  /** Add formula-based conditional formatting */
  addConditionalFormatFormula(firstRow: number, firstCol: number, lastRow: number, lastCol: number, formula: string, format: RuscFormat): void
  /** Add icon set conditional formatting */
  addConditionalFormatIconSet(firstRow: number, firstCol: number, lastRow: number, lastCol: number, iconType: string): void
  /** Set page margins (in inches) */
  setMargins(left: number, right: number, top: number, bottom: number, header: number, footer: number): void
  /** Set page orientation to portrait */
  setPortrait(): void
  /** Set page orientation to landscape */
  setLandscape(): void
  /** Set paper size (1=Letter, 9=A4, etc.) */
  setPaperSize(paperSize: number): void
  /** Set header text */
  setHeader(header: string): void
  /** Set footer text */
  setFooter(footer: string): void
  /** Set print area */
  setPrintArea(firstRow: number, firstCol: number, lastRow: number, lastCol: number): void
  /** Set print gridlines */
  setPrintGridlines(enable: boolean): void
  /** Center content horizontally on the page when printing */
  setPrintCenterHorizontally(enable: boolean): void
  /** Center content vertically on the page when printing */
  setPrintCenterVertically(enable: boolean): void
  /** Fit worksheet to N pages wide by M pages tall when printing */
  setPrintFitToPages(width: number, height: number): void
  /** Set print scale as a percentage (10-400) */
  setPrintScale(scale: number): void
  /** Set the first page number for printing */
  setPrintFirstPageNumber(pageNumber: number): void
  /** Enable/disable black and white printing */
  setPrintBlackAndWhite(enable: boolean): void
  /** Enable/disable draft quality printing */
  setPrintDraft(enable: boolean): void
  /** Enable/disable printing of row and column headings */
  setPrintHeadings(enable: boolean): void
  /** Repeat rows at the top of each printed page */
  setRepeatRows(firstRow: number, lastRow: number): void
  /** Repeat columns at the left of each printed page */
  setRepeatColumns(firstCol: number, lastCol: number): void
  /** Scale header and footer with document */
  setHeaderFooterScaleWithDoc(enable: boolean): void
  /** Align header and footer with page margins */
  setHeaderFooterAlignWithPage(enable: boolean): void
  /** Set the worksheet tab color */
  setTabColor(color: string): void
  /** Hide or show the worksheet */
  setHidden(enable: boolean): void
  /** Set the worksheet zoom level (10-400) */
  setZoom(zoom: number): void
  /** Set the default cell selection when opening the worksheet */
  setSelection(firstRow: number, firstCol: number, lastRow: number, lastCol: number): void
  /** Set which cell appears in the top-left corner when opening the worksheet */
  setTopLeftCell(row: number, col: number): void
  /** Protect the worksheet from editing */
  protect(): void
  /** Protect the worksheet with a password */
  protectWithPassword(password: string): void
  /** Protect the worksheet with granular protection options */
  protectWithOptions(options: RuscProtectionOptions): void
  /** Protect the worksheet with a password and granular protection options */
  protectWithPasswordAndOptions(password: string, options: RuscProtectionOptions): void
  /** Insert a chart at the specified cell position */
  insertChart(row: number, col: number, chart: RuscChart): void
  /** Insert a chart at the specified cell position with pixel offsets */
  insertChartWithOffset(row: number, col: number, chart: RuscChart, xOffset: number, yOffset: number): void
  /** Insert an image at the specified cell position */
  insertImage(row: number, col: number, image: RuscImage): void
  /** Insert an image at the specified cell position with pixel offsets */
  insertImageWithOffset(row: number, col: number, image: RuscImage, xOffset: number, yOffset: number): void
  /** Insert an image that fits to a cell */
  insertImageFitToCell(row: number, col: number, image: RuscImage, keepAspectRatio: boolean): void
  /** Add a table to the worksheet */
  addTable(firstRow: number, firstCol: number, lastRow: number, lastCol: number, table: RuscTable): void
  /** Add a sparkline to a single cell */
  addSparkline(row: number, col: number, sparkline: RuscSparkline): void
  /** Add a sparkline group to a range of cells */
  addSparklineGroup(firstRow: number, firstCol: number, lastRow: number, lastCol: number, sparkline: RuscSparkline): void
  /** Insert a button at the specified cell position */
  insertButton(row: number, col: number, button: RuscButton): void
  /** Insert a button at the specified cell position with pixel offsets */
  insertButtonWithOffset(row: number, col: number, button: RuscButton, xOffset: number, yOffset: number): void
  /** Insert a shape (textbox) at the specified cell position */
  insertShape(row: number, col: number, shape: RuscShape): void
  /** Insert a shape (textbox) at the specified cell position with pixel offsets */
  insertShapeWithOffset(row: number, col: number, shape: RuscShape, xOffset: number, yOffset: number): void
}
